import assert from 'node:assert/strict';
import {createRequire,syncBuiltinESMExports} from 'node:module';
import {writeFileSync} from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import http from 'node:http'; import https from 'node:https'; import net from 'node:net'; import dgram from 'node:dgram';
const root=process.env.AUDIT_RESOURCE_REPO!,tmp=process.env.AUDIT_RESOURCE_TMP!;
const load=(p:string)=>import(pathToFileURL(path.join(root,p)).href),require=createRequire(path.join(root,'package.json'));
let network=0;const block=()=>{network++;throw new Error('AUDIT_NETWORK_BLOCKED');};
globalThis.fetch=block as any;http.request=block as any;http.get=block as any;https.request=block as any;https.get=block as any;net.Socket.prototype.connect=block as any;dgram.createSocket=block as any;syncBuiltinESMExports();
const cases:any[]=[], evidence:any={};
async function check(id:string,category:string,fn:()=>any){try {const detail=await fn();cases.push({id,category,status:'PASS',evidence:detail??{}});}catch(e:any){cases.push({id,category,status:'FAIL',error:e.message});}}
async function main(){
 const Database=require('better-sqlite3'),{drizzle}=require('drizzle-orm/better-sqlite3');
 const {runMigrations}=await load('backend/watchdog_api/db/migrations/index.ts');
 const {RunSubmissionSchema}=await load('backend/watchdog_api/api/schemas.ts');
 const {RunRepository}=await load('backend/watchdog_api/db/repositories/runs.ts');
 const {RunOrchestrator}=await load('backend/watchdog_api/services/run_orchestrator.ts');
 const {ObservationRepository,AnalysisResultRepository}=await load('backend/watchdog_api/db/repositories/data.ts');
 const {ArtifactRepository}=await load('backend/watchdog_api/db/repositories/artifacts.ts');
 const {LocalFileSystemStore}=await load('backend/watchdog_api/storage/object_store/index.ts');
 const {JH16Analyzer}=await load('backend/watchdog_api/analytics/jh16.ts');
 const {canonicalHash}=await load('backend/watchdog_api/domain/canonical.ts');
 const {exportJson}=await load('backend/watchdog_api/services/export.ts');
 const {tracer}=await load('backend/watchdog_api/utils/tracer.ts');
 const traces:any[]=[];(tracer as any).writeLog=(_a:any,_b:any,data:any)=>traces.push(data);tracer.setMode('TRACE');
 const sqlite=new Database(path.join(tmp,'runs.sqlite'));sqlite.pragma('foreign_keys=ON');runMigrations(sqlite);
 const db=drizzle(sqlite), rr=new RunRepository(db), obs=new ObservationRepository(db), ar=new AnalysisResultRepository(db), art=new ArtifactRepository(db), store=new LocalFileSystemStore(path.join(tmp,'objects'));
 const source=rr.createRun({runType:'ACQUISITION',config:{synthetic:true}});
 const base={seriesId:'',entityId:'audit_entity',queryText:'synthetic',language:'en',queryExpansionMode:'STRICT_CANONICAL',retrievedAt:'2026-10-09T00:00:00.000Z',sourceId:'audit-source',sourceAdapterVersion:'fixture-1',qualityFlags:['COUNT_PARSE_UNCERTAIN']};
 const rows=[{...base,queryRole:'popularity',numericValue:100,isMissing:false},{...base,queryRole:'harm',numericValue:null,isMissing:true,missingReason:'RATE_LIMITED'}];obs.insertMany(source,rows);
 const input={type:'ANALYSIS',config:{source_run_id:source,method_id:'jh16_faithful',method_params:{reference_scores:{audit_entity:7}},method_spec_id:'audit-missing-unapproved',method_spec_hash:'unapproved-fixture-hash',personal_credentials:true,plan:[{entityId:'audit_only',dimension:'custom',renderedQuery:'synthetic-only'}]}};
 const validation=RunSubmissionSchema.safeParse(input);
 const safeInput={type:'ANALYSIS',config:{source_run_id:source,method_id:'jh16_faithful',method_params:{reference_scores:{audit_entity:7}}}};
 const parsed=validation.success?validation.data:RunSubmissionSchema.parse(safeInput),stripped=validation.success?Object.keys(input.config).filter(k=>!(k in parsed.config)):[];
 const orchestrator=new RunOrchestrator(db,store);
 const accepted=rr.createRun({runType:parsed.type,config:parsed.config});await orchestrator.executeRun(accepted);
 const direct=rr.createRun({runType:'ANALYSIS',config:input.config});await orchestrator.executeRun(direct);
 evidence.schema={rejectedAtSchema:!validation.success,stripped,apiPathStatus:rr.getRun(accepted).status,directPathStatus:rr.getRun(direct).status,apiResultCount:ar.getByRunId(accepted).length};
 await check('A4-WD-001.A.schema-drops-method-pin','reproduction',()=>{assert.ok(validation.success,'Schema now rejects unsupported fields (bug reproduction no longer passes)');assert.ok(stripped.includes('method_spec_id'));assert.equal(rr.getRun(accepted).status,'COMPLETED');assert.equal(rr.getRun(direct).status,'FAILED');return evidence.schema;});
 await check('A4-WD-001.B.reject-or-preserve-unsupported-setting','acceptance',()=>{if(!validation.success)return {rejectedBeforeExecution:true};assert.ok(!stripped.includes('method_spec_id'),'RunSubmissionSchema silently removes requested method identity before actual executor');assert.notEqual(rr.getRun(accepted).status,'COMPLETED');});
 const mf=art.getManifest(accepted),manifest=JSON.parse((await store.get(mf.object_uri)).toString());
 const exportBody=JSON.parse(exportJson({runId:accepted,results:ar.getByRunId(accepted),missingObservations:obs.getByRunId(accepted).filter((x:any)=>x.isMissing).map((x:any)=>({entity_id:x.entityId,query_role:x.queryRole,missing_reason:x.missingReason})),qualityFlags:obs.getByRunId(accepted).flatMap((x:any)=>x.qualityFlags)}));
 evidence.reuse={sourceMissing:obs.getByRunId(source).filter((x:any)=>x.isMissing).length,manifestMissing:manifest.missing_observations.length,manifestFlags:manifest.quality_flags,manifestInputHashes:manifest.analyses.map((x:any)=>x.input_hashes),exportMissing:exportBody.missing_observations.length,sourceReferencePresent:manifest.effective_config.source_run_id===source,resultMissing:ar.getByRunId(accepted).filter((x:any)=>x.isMissing).length};
 await check('A4-WD-002.A.reused-source-disclosures-lost','reproduction',()=>{assert.equal(evidence.reuse.sourceMissing,1);assert.equal(evidence.reuse.manifestMissing,0);assert.equal(evidence.reuse.exportMissing,0);assert.ok(evidence.reuse.resultMissing>0);return evidence.reuse;});
 await check('A4-WD-002.B.manifest-retains-reused-input-missingness','acceptance',()=>{assert.ok(manifest.missing_observations.some((x:any)=>x.missing_reason==='RATE_LIMITED'));assert.ok(manifest.quality_flags.includes('COUNT_PARSE_UNCERTAIN'));assert.ok(manifest.analyses.some((x:any)=>x.input_hashes.length));});
 await check('A4-WD-M01.object-key-order','contract',async()=>{const reversed={method_params:parsed.config.method_params,method_id:parsed.config.method_id,source_run_id:source};assert.equal(canonicalHash(parsed.config),canonicalHash(reversed));const r=rr.createRun({runType:'ANALYSIS',config:reversed});await orchestrator.executeRun(r);assert.deepEqual(ar.getByRunId(r),ar.getByRunId(accepted));return {invariant:'effective configuration hash and domain results; run IDs and timestamps are intentionally excluded'};});
 await check('A4-WD-M02.unique-observation-order','contract',()=>{const analyzer=new JH16Analyzer(),cfg={method_id:'jh16_faithful',method_version:'1.1.0',parameters:{reference_scores:{audit_entity:7}}};assert.deepEqual(analyzer.analyze(rows,cfg),analyzer.analyze([...rows].reverse(),cfg));return {invariant:'set of unique entity/role observations, including missingness; not message/list chronology'};});
 const duplicates=[{...base,queryRole:'popularity',numericValue:100,isMissing:false},{...base,queryRole:'popularity',numericValue:200,isMissing:false},{...base,queryRole:'harm',numericValue:50,isMissing:false}];
 const analyzer=new JH16Analyzer(),cfg={method_id:'jh16_faithful',method_version:'1.1.0',parameters:{reference_scores:{audit_entity:7}}};
 const forward=analyzer.analyze(duplicates,cfg),reverse=analyzer.analyze([...duplicates].reverse(),cfg);
 evidence.duplicate={forwardHi:forward.find((x:any)=>x.metricKey==='Hi').valueNumeric,reverseHi:reverse.find((x:any)=>x.metricKey==='Hi').valueNumeric};
 await check('A4-WD-003.A.ambiguous-input-silent-last-wins','reproduction',()=>{assert.notEqual(evidence.duplicate.forwardHi,evidence.duplicate.reverseHi);return evidence.duplicate;});
 await check('A4-WD-003.B.ambiguity-explicit-or-policy','acceptance',()=>{assert.throws(()=>analyzer.analyze(duplicates,cfg),/ambig|duplic|policy/i,'Missing explicit duplicate-resolution policy must not silently select last observation');});
 const failure=rr.createRun({runType:'ACQUISITION',config:{source_id:'audit-synthetic',source_params:{},language:'en',query_expansion_mode:'STRICT_CANONICAL',plan:[{entityId:'audit_entity',dimension:'popularity',renderedQuery:'synthetic'}]}});
 const failureAdapter={adapter_version:'fixture-1',capabilities:()=>['result_count'],validate_params:()=>({valid:true,normalized_params:{}}),fetch:async()=>({status:'FAILED',payload:Buffer.from('synthetic-failure'),http_status:503}),normalize:()=>{throw new Error('must not normalize failed fetch');}};
 await new RunOrchestrator(db,store,async()=>failureAdapter).executeRun(failure);
 await check('A4-WD-M03.failed-fetch-not-completed','contract',()=>{assert.equal(rr.getRun(failure).status,'FAILED');assert.equal(art.getManifest(failure),undefined);assert.ok(sqlite.prepare('SELECT count(*) n FROM fetch_events WHERE run_id=?').get(failure).n);return {boundary:'controlled SourceAdapter transport seam; actual orchestrator/archive/SQLite; no real supplier request'};});
 sqlite.close();
 const reopened=new Database(path.join(tmp,'runs.sqlite')),rr2=new RunRepository(drizzle(reopened));
 await check('A4-WD-M04.completed-run-restart','integration',async()=>{assert.equal(rr2.getRun(accepted).status,'COMPLETED');const reopenedArt=new ArtifactRepository(drizzle(reopened));const reopenedMf=reopenedArt.getManifest(accepted);const reopenedStore=new LocalFileSystemStore(path.join(tmp,'objects'));const saved=JSON.parse((await reopenedStore.get(reopenedMf.object_uri)).toString());assert.equal(saved.effective_config.source_run_id,source);assert.deepEqual(saved,manifest);return {boundary:'actual SQLite close/reopen and new store instance read of filesystem manifest; not OS crash'};});reopened.close();
 await check('A4-WD-M05.network-denied','contract',()=>{assert.equal(network,0);return {attemptedExternalConnections:network};});
 writeFileSync(process.env.AUDIT_RESOURCE_OUT!,JSON.stringify({schema:'klbt.audit.pass4-receipt/1',repo:'klb-t/Watchdog-JH16',sha:process.env.AUDIT_RESOURCE_SHA,categories:'PASS reproduction proves bug, never product correctness',cases,evidence},null,2)+'\n');
 console.log(JSON.stringify({cases:cases.length,counts:cases.reduce((a:any,x:any)=>(a[x.status]=(a[x.status]||0)+1,a),{})}));
 process.exitCode=cases.some(x=>x.status==='FAIL')?1:0;
}
main().catch(e=>{console.error(e);process.exitCode=2;});
