"""Compile canonical data references and embed onboarding packs deterministically."""
from copy import deepcopy
from pathlib import Path
import argparse
import hashlib
import json

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data"
FILES = {
    "kOnboardingPack": DATA / "profiles/user.pack",
    "kOnboardingScenario": DATA / "onboarding/scenario.pack",
    "kOnboardingPresentation": DATA / "onboarding/ui.pack",
}
OUT = Path(__file__).with_name("builtin.inc")
WEB_OUT = ROOT / "web/src/onboarding/generated/ui.json"


def read_document(path, trail=()):
    path = path.resolve()
    if not path.is_relative_to(DATA.resolve()):
        raise ValueError("data reference leaves the canonical data directory")
    if path in trail:
        raise ValueError("cyclic data reference")
    return expand(json.loads(path.read_bytes().decode("utf-8")), trail + (path,))


def expand(value, trail=()):
    if isinstance(value, dict):
        if "$include" in value:
            if set(value) != {"$include"} or not isinstance(value["$include"], str):
                raise ValueError("data include needs exactly one string reference")
            return read_document(DATA / value["$include"], trail)
        return {key: expand(item, trail) for key, item in value.items()}
    if isinstance(value, list):
        return [expand(item, trail) for item in value]
    return value


def assign_pointer(target, pointer, value):
    if not isinstance(pointer, str) or not pointer.startswith("/"):
        raise ValueError("runtime binding needs a non-root RFC6901 pointer")
    tokens = pointer[1:].split("/")
    for token in tokens:
        # An escape must be one of the two RFC6901 escape forms.
        cursor = 0
        while cursor < len(token):
            if token[cursor] == "~":
                if cursor + 1 == len(token) or token[cursor + 1] not in "01":
                    raise ValueError("malformed RFC6901 escape")
                cursor += 2
            else:
                cursor += 1
    tokens = [token.replace("~1", "/").replace("~0", "~") for token in tokens]
    cursor = target
    for token in tokens[:-1]:
        if token not in cursor:
            cursor[token] = {}
        if not isinstance(cursor[token], dict):
            raise ValueError("overlapping runtime binding pointers")
        cursor = cursor[token]
    if tokens[-1] in cursor:
        raise ValueError("overlapping runtime binding pointers")
    cursor[tokens[-1]] = deepcopy(value)


def compile_layer_bindings(pack):
    definition = pack.get("runtime_definition")
    if not isinstance(definition, dict):
        return pack
    directive = definition.get("defaults")
    if not isinstance(directive, dict) or "$layer_bindings" not in directive:
        return pack
    if set(directive) != {"$layer_bindings"}:
        raise ValueError("runtime defaults directive has additional members")
    binding_name = directive["$layer_bindings"]
    if not isinstance(binding_name, str) or not isinstance(pack.get(binding_name), dict):
        raise ValueError("runtime defaults directive names no binding map")
    entries = {}
    for entry in pack.get("entries", []):
        key = entry["key"]
        if key in entries:
            raise ValueError("duplicate default layer key")
        entries[key] = entry["value"]
    defaults = {}
    pointers = list(pack[binding_name])
    for first in pointers:
        for second in pointers:
            if first != second and second.startswith(first + "/"):
                raise ValueError("overlapping runtime binding pointers")
    for pointer, key in pack[binding_name].items():
        if key not in entries:
            raise ValueError("runtime binding names no default entry")
        assign_pointer(defaults, pointer, entries[key])
    definition["defaults"] = defaults
    return pack


def documents():
    result = {name: read_document(path) for name, path in FILES.items()}
    compile_layer_bindings(result["kOnboardingPack"])
    return result


def serialized(value):
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def generated():
    docs = documents()
    lines = ["// Generated by gen_onboarding_pack.py; edit canonical .pack data instead.\n"]
    for name, value in docs.items():
        raw = serialized(value)
        if ')loom_onboard"' in raw:
            raise ValueError("raw string delimiter collision")
        lines.append(f'static constexpr char {name}[] = R"loom_onboard({raw})loom_onboard";\n')
    ui = serialized(docs["kOnboardingPresentation"])
    return {OUT: "".join(lines), WEB_OUT: ui}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = generated()
    if args.check:
        for path, content in outputs.items():
            if not path.exists() or path.read_bytes() != content.encode("utf-8"):
                raise SystemExit("onboarding generated data is stale: " + str(path.relative_to(ROOT)))
    else:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content.encode("utf-8"))


if __name__ == "__main__":
    main()
