"""Embed exact canonical onboarding data; --check detects stale generated bytes."""
from pathlib import Path
import argparse
import json

ROOT = Path(__file__).resolve().parents[2]
FILES = {
    "kOnboardingPack": ROOT / "data/profiles/user.pack",
    "kOnboardingScenario": ROOT / "data/onboarding/scenario.pack",
}
OUT = Path(__file__).with_name("builtin.inc")

def generated():
    lines = ["// Generated by gen_onboarding_pack.py; edit canonical .pack data instead.\n"]
    for name, path in FILES.items():
        raw = path.read_text(encoding="utf-8")
        json.loads(raw)
        if ')loom_onboard"' in raw:
            raise ValueError("raw string delimiter collision")
        lines.append(f'static constexpr char {name}[] = R"loom_onboard({raw})loom_onboard";\n')
    return "".join(lines)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generated()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            raise SystemExit("onboarding embedded data is stale")
    else:
        OUT.write_text(text, encoding="utf-8")
