#!/usr/bin/env python3
"""Prove edited preset data reach real native paths without changing the repo.

Requires a fresh development kernel build and compile_commands.json. Each
variant copies the actual preset consumer TU, regenerates its own include and
links that object before the actual libloom_core.a. Inputs, generated bytes,
commands, results and hashes remain in a new caller-selected output directory.
"""

import argparse
import hashlib
import json
import shlex
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[4]


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_json(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def canonical_hash(value):
    encoded = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def compile_recipe(build_dir, source):
    entries = json.loads((build_dir / "compile_commands.json").read_text(encoding="utf-8"))
    entry = next(item for item in entries if Path(item["file"]).resolve() == source.resolve())
    tokens = entry.get("arguments") or shlex.split(entry["command"])
    compiler, flags = tokens[0], []
    index = 1
    while index < len(tokens):
        token = tokens[index]
        if token == "-o":
            index += 2
            continue
        if token == "-c" or token == entry["file"]:
            index += 1
            continue
        flags.append(token)
        index += 1
    return compiler, flags, Path(entry["directory"]), entry


def verify_positive(result, expected, raw_source):
    assert result["all_paths_equal"] is True
    assert result["checked_preset"] == expected
    assert result["compatibility_view"] == expected
    assert set(result["paths"]) == {"config_get", "loom_config_defaults", "effective", "settings", "default_open"}
    assert all(value == expected for value in result["paths"].values())
    assert result["stored_override_present"] is False
    assert result["preset_written_to_config"] is False
    assert result["config_file_exists_before"] is False
    assert result["config_file_exists_after_reads"] is False
    assert result["config_file_unchanged"] is True
    provenance = result["provenance"]
    assert provenance["preset_source"] == "embedded_data"
    assert provenance["preset_document"]["source_sha256"] == hashlib.sha256(raw_source).hexdigest()
    assert provenance["hashes"]["preset"] == canonical_hash(expected)
    assert provenance["hashes"]["effective"] == canonical_hash(expected)
    overlay = result["overlay"]
    overridden = dict(expected)
    overridden.update(overlay["override"])
    assert overlay["expected_effective"] == overridden
    assert overlay["config_get_after_restart"] == overlay["override"]
    for key in ["effective_after_restart", "settings_effective_after_restart", "opened_options"]:
        assert overlay[key] == overridden
    for key in ["all_effective_paths_equal", "shallow_initial_baselines_replaced",
                "raw_override_preserved", "config_file_unchanged_on_restart"]:
        assert overlay[key] is True
    assert overridden["initial_baselines"] == overlay["override"]["initial_baselines"]


def verify_negative(result):
    assert result["failed_closed"] is True
    assert set(result["results"]) == {"checked_preset", "effective", "settings", "default_open"}
    for value in result["results"].values():
        assert value["ok"] is False and value["code"] == "invalid_argument"
    assert all(value["threw"] is True for value in result["legacy"].values())
    assert result["ledger_created"] is False
    assert result["ledger_parent_created"] is False
    assert result["config_created"] is False


def run_proof(repo, build_dir, output):
    if output.exists() and any(output.iterdir()):
        raise ValueError("output directory must be new or empty; existing evidence is never overwritten")
    output.mkdir(parents=True, exist_ok=True)
    native_source = repo / "loom/src/core/config_usage_policy.cpp"
    generator = repo / "loom/src/policy/gen_usage_policy.py"
    generic_probe = repo / "loom/src/policy/tests/preset_paths_probe.cc"
    negative_probe = repo / "loom/src/policy/tests/negative_preset_probe.cc"
    canonical_source = repo / "loom/data/policy/usage_policy.pack"
    canonical_include = repo / "loom/src/policy/usage_policy_preset.inc"
    header = repo / "loom/include/loom/usage_policy.h"
    kernel = build_dir / "libloom_core.a"
    libraries = [kernel, build_dir / "libloom_sqlite3_amalgamation.a", build_dir / "libloom_miniz.a"]
    watched = [native_source, generator, generic_probe, negative_probe, canonical_source, canonical_include, header, *libraries]
    initial_hashes = {str(path.relative_to(repo)): sha256(path) for path in watched}
    compiler, flags, compile_cwd, entry = compile_recipe(build_dir, native_source)
    commands, cases = [], {}

    def record_run(argv, cwd, prefix):
        completed = subprocess.run(argv, cwd=cwd, capture_output=True)
        stdout = output / (prefix + ".stdout.txt")
        stderr = output / (prefix + ".stderr.txt")
        stdout.write_bytes(completed.stdout)
        stderr.write_bytes(completed.stderr)
        commands.append({"argv": [str(value) for value in argv], "cwd": str(cwd),
                         "exit_code": completed.returncode,
                         "stdout": str(stdout.relative_to(output)), "stderr": str(stderr.relative_to(output))})
        write_json(output / "commands.json", commands)
        if completed.returncode:
            raise RuntimeError(f"{prefix} failed; complete stdout/stderr retained in output directory")
        return completed.stdout

    canonical_bytes = canonical_source.read_bytes()
    canonical = json.loads(canonical_bytes.decode("utf-8"))
    edited = dict(canonical)
    edited.update({"growth_factor": 12.5, "baseline_window": 7, "ledger_busy_timeout_ms": 123,
                   "include_reservations": False,
                   "initial_baselines": {"synthetic/source-edit-v1": {"bytes": 12345, "tokens": None}},
                   "source_edit_extension": {"kind": "synthetic", "items": [1, None, "opaque"]}})
    missing = dict(edited)
    del missing["include_reservations"]
    factor_one = dict(edited)
    factor_one["growth_factor"] = 1.0
    variants = [
        ("canonical", canonical, canonical_bytes, False, False),
        ("source-edited", edited, None, True, False),
        ("invalid-missing-field", missing, None, True, True),
        ("invalid-growth-factor", factor_one, None, True, True),
    ]
    for name, expected, original_bytes, isolated, invalid in variants:
        case_root = output / name
        (case_root / "src/core").mkdir(parents=True)
        (case_root / "src/policy").mkdir(parents=True)
        source_input = case_root / "usage_policy.pack"
        source_input.write_bytes(original_bytes if original_bytes is not None else
                                 (json.dumps(expected, ensure_ascii=False, indent=2) + "\n").encode("utf-8"))
        consumer = case_root / "src/core/config_usage_policy.cpp"
        shutil.copyfile(native_source, consumer)
        generated = case_root / "src/policy/usage_policy_preset.inc"
        record_run([sys.executable, str(generator), "--source", str(source_input), "--output", str(generated)],
                   repo, name + "/generate")
        record_run([sys.executable, str(generator), "--source", str(source_input), "--output", str(generated), "--check"],
                   repo, name + "/generated-check")
        objects = []
        if isolated:
            variant_object = case_root / "config_usage_policy.o"
            record_run([compiler, *flags, "-c", str(consumer), "-o", str(variant_object)],
                       compile_cwd, name + "/compile-consumer")
            objects.append(variant_object)
        probe_source = case_root / "probe.cc"
        shutil.copyfile(negative_probe if invalid else generic_probe, probe_source)
        executable = case_root / "probe"
        record_run([compiler, *flags, "-pthread", str(probe_source), *map(str, objects), *map(str, libraries),
                    "-lssl", "-lcrypto", "-ldl", "-lm", "-o", str(executable)],
                   compile_cwd, name + "/link-native-probe")
        result = json.loads(record_run([str(executable), str(case_root / "data")], repo, name + "/run-native-probe"))
        if invalid:
            verify_negative(result)
        else:
            verify_positive(result, expected, source_input.read_bytes())
        write_json(case_root / "result.json", result)
        cases[name] = {"passed": True, "isolated_consumer_object": isolated,
                       "variant_object_precedes_actual_kernel": isolated,
                       "source_sha256": sha256(source_input), "generated_sha256": sha256(generated),
                       "consumer_sha256": sha256(consumer), "probe_source_sha256": sha256(probe_source),
                       "probe_binary_sha256": sha256(executable), "result": str((case_root / "result.json").relative_to(output))}
    final_hashes = {str(path.relative_to(repo)): sha256(path) for path in watched}
    assert initial_hashes == final_hashes, "proof input or actual kernel changed during execution"
    artifacts = {str(path.relative_to(output)): {"sha256": sha256(path), "bytes": path.stat().st_size}
                 for path in sorted(output.rglob("*")) if path.is_file()}
    manifest = {"schema": "loom.usage_preset_source_edit_proof/1", "passed": True,
                "cases": cases, "inputs": initial_hashes, "compile_command_entry": entry,
                "commands": commands, "artifacts": artifacts,
                "repository_inputs_unchanged": True, "paid_provider_calls": 0,
                "scope": "actual native consumer objects and actual static kernel; synthetic inputs only"}
    write_json(output / "manifest.json", manifest)
    return manifest


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=REPO_ROOT)
    parser.add_argument("--build-dir", type=Path)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args(argv)
    repo = args.repo.resolve()
    build = args.build_dir.resolve() if args.build_dir else repo / "loom/build/dev"
    output = args.output_dir.resolve()
    try:
        manifest = run_proof(repo, build, output)
    except (OSError, ValueError, StopIteration, AssertionError, RuntimeError) as problem:
        parser.exit(1, f"preset proof failed: {problem}\n")
    print(json.dumps({"passed": manifest["passed"], "cases": len(manifest["cases"]),
                      "manifest": str(output / "manifest.json"), "paid_provider_calls": 0}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
