#!/usr/bin/env python3
"""Compile independent JSON-content .prompt files; --check verifies the copy."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'data' / 'prompts'
TARGET = ROOT / 'src' / 'extract' / 'prompt_contract_data.inc'

def generated() -> str:
    contracts = {}
    sources = []
    for path in sorted(SOURCE.glob('*.prompt')):
        raw = path.read_bytes()
        doc = json.loads(raw.decode('utf-8'))
        if doc.get('schema') != 'loom.analysis_prompt/1' or not isinstance(doc.get('id'), str) or not doc['id']:
            raise ValueError(f'{path}: missing/invalid schema or id')
        if doc['id'] in contracts:
            raise ValueError(f'{path}: duplicate prompt id {doc["id"]}')
        contracts[doc['id']] = {'file': path.name, 'definition': doc, 'source_hash': hashlib.sha256(raw).hexdigest()}
        sources.append(f'// {path.name}: sha256 {hashlib.sha256(raw).hexdigest()}')
    # Provider body bytes retain the source's parameter order; canonical
    # identity hashing is performed separately by the native registry.
    payload = json.dumps(contracts, ensure_ascii=False, separators=(',', ':'))
    delimiter = 'LOOM_PROMPTS'
    if f'){delimiter}"' in payload:
        raise ValueError('raw-literal delimiter occurs in prompt data')
    return '// Generated by src/extract/gen_prompt_contracts.py; do not edit.\n' + '\n'.join(sources) + '\n' + 'constexpr std::string_view kBuiltinPromptData = R"' + delimiter + '(' + payload + ')' + delimiter + '";\n'

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generated()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding='utf-8') != text:
            print('prompt_contract_data.inc is stale; run src/extract/gen_prompt_contracts.py')
            return 1
    else:
        TARGET.write_text(text, encoding='utf-8')
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
