#!/usr/bin/env python3
"""Compile independent method metadata and opaque recipe records, offline."""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'data' / 'prompts'
TARGET = ROOT / 'src' / 'extract' / 'prompt_method_data.inc'

def reject_constant(value: str):
    raise ValueError('nonfinite JSON constant: ' + value)

def generated() -> str:
    path = SOURCE / 'analysis_methods.pack'
    raw = path.read_bytes()
    data = json.loads(raw.decode('utf-8'), parse_constant=reject_constant)
    if data.get('schema') != 'loom.analysis_methods/1':
        raise ValueError('analysis_methods.pack: invalid schema')
    recipes = {}
    sources = [f'// analysis_methods.pack: sha256 {hashlib.sha256(raw).hexdigest()}']
    for path in sorted(SOURCE.glob('*.recipe')):
        raw = path.read_bytes()
        doc = json.loads(raw.decode('utf-8'), parse_constant=reject_constant)
        id_ = doc.get('id')
        if not isinstance(id_, str) or not id_ or id_ in recipes:
            raise ValueError(f'{path}: missing or duplicate recipe id')
        sha = hashlib.sha256(raw).hexdigest()
        recipes[id_] = {'definition': doc, 'source_hash': sha, 'file': path.name}
        sources.append(f'// {path.name}: sha256 {sha}')
    data['recipe_records'] = recipes
    # Source identity describes authored bytes, not an effective overlay hash.
    data['source_hash'] = hashlib.sha256((SOURCE / 'analysis_methods.pack').read_bytes()).hexdigest()
    payload = json.dumps(data, ensure_ascii=False, separators=(',', ':'), allow_nan=False)
    delimiter = 'LOOM_METHOD_DATA'
    if f'){delimiter}"' in payload:
        raise ValueError('raw-literal delimiter collision')
    return ('// Generated by src/extract/gen_prompt_methods.py; do not edit.\n'
            + '\n'.join(sources) + '\nconstexpr std::string_view kBuiltinMethodData = R"'
            + delimiter + '(' + payload + ')' + delimiter + '";\n')

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generated()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding='utf-8') != text:
            print('prompt_method_data.inc is stale; run src/extract/gen_prompt_methods.py')
            return 1
        return 0
    if TARGET.exists() and TARGET.read_text(encoding='utf-8') == text:
        return 0
    temporary = TARGET.with_name(TARGET.name + '.tmp')
    try:
        with temporary.open('w', encoding='utf-8') as output:
            output.write(text)
            output.flush()
            os.fsync(output.fileno())
        temporary.replace(TARGET)
    finally:
        temporary.unlink(missing_ok=True)
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
