#!/usr/bin/env python3
"""Embeds the paradigm-engine data pack (loom/data) into the library.

Writes loom/src/kb/pack_embedded.inc: every file listed in
loom/data/pack.json (plus pack.json itself) as raw-string chunks, so phones
and the CLI have the built-in pack without shipping a directory.
tests/test_kb_pack.cpp fails when the embedded copy and the directory
differ, so run this after editing any file under loom/data:

    python3 loom/tools/gen_kb_pack.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT = ROOT / "src/kb/pack_embedded.inc"
DELIM = "LOOMKB"
CHUNK = 8000  # bytes; keeps every literal far below the 64 KiB -pedantic limit


def chunks(text):
    raw = text.encode("utf-8")
    out, start = [], 0
    while start < len(raw):
        end = min(start + CHUNK, len(raw))
        while end < len(raw) and (raw[end] & 0xC0) == 0x80:  # never split a UTF-8 sequence
            end -= 1
        out.append(raw[start:end].decode("utf-8"))
        start = end
    return out or [""]


def main():
    manifest = json.loads((DATA / "pack.json").read_text(encoding="utf-8"))
    paths = ["pack.json"] + [f["path"] for f in manifest["files"]]
    lines = [
        "// Generated by loom/tools/gen_kb_pack.py from loom/data. Do not edit.",
        "// Regenerate after changing any pack file; test_kb_pack checks equality.",
        "// NOLINTBEGIN",
    ]
    table = []
    for i, p in enumerate(paths):
        text = (DATA / p).read_text(encoding="utf-8")
        if f"){DELIM}\"" in text:
            raise SystemExit(f"{p}: contains the raw-string delimiter")
        lines.append(f"const char* const kPackChunks{i}[] = {{")
        for c in chunks(text):
            lines.append(f'    R"{DELIM}({c}){DELIM}",')
        lines.append("    nullptr};")
        table.append(f'    {{"{p}", kPackChunks{i}}},')
    lines.append("struct EmbeddedPackFile {")
    lines.append("  const char* path;")
    lines.append("  const char* const* chunks;")
    lines.append("};")
    lines.append("const EmbeddedPackFile kEmbeddedPack[] = {")
    lines.extend(table)
    lines.append("};")
    lines.append("// NOLINTEND")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"embedded {len(paths)} files -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
