#!/usr/bin/env python3
"""Export core/semantic.py's rule tables as Loom policy data.

Writes loom/src/semantic/builtin_rules.json.inc: a C++ raw string holding the
JSON form of AnalyzerRules (entity patterns, topic keywords, relation
patterns) taken from the Python module itself, so the C++ analyzer starts from
exactly the same data. tests/compat verifies the embedded copy stays in sync.

Usage: python3 loom/tools/gen_semantic_rules.py
"""
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from core import semantic  # noqa: E402

OUT = REPO / "loom" / "src" / "semantic" / "builtin_rules.json.inc"

FLAG_NAMES = [(re.IGNORECASE, "IGNORECASE"), (re.MULTILINE, "MULTILINE"), (re.DOTALL, "DOTALL")]


def flag_list(flags: int) -> list:
    return [name for bit, name in FLAG_NAMES if flags & bit]


def relation_patterns() -> list:
    # The relation regexes are local to extract_relations(); read them from the
    # source so there is a single source of truth.
    src = pathlib.Path(semantic.__file__).read_text(encoding="utf-8")
    body = src[src.index("def extract_relations"):src.index("def analyse")]
    pats = re.findall(r"re\.compile\(\s*r'(.*?)',\s*re\.I,\s*\)", body, re.S)
    confs = [float(c) for c in re.findall(r"confidence=([0-9.]+)", body)]
    preds = re.findall(r"predicate=RelationType\.(\w+)", body)
    assert len(pats) == len(confs) == len(preds) == 2, (pats, confs, preds)
    return [
        {"predicate": semantic.RelationType[p].value, "pattern": pat, "flags": ["IGNORECASE"], "confidence": c}
        for pat, c, p in zip(pats, confs, preds)
    ]


def build() -> dict:
    return {
        "entity_patterns": [
            {"entity_type": et.value, "pattern": pat.pattern, "flags": flag_list(pat.flags)}
            for et, pat in semantic._PATTERNS
        ],
        "topics": [{"topic": t, "keywords": kws} for t, kws in semantic._TOPIC_KEYWORDS.items()],
        "relation_patterns": relation_patterns(),
    }


def main() -> None:
    text = json.dumps(build(), indent=2, ensure_ascii=False)
    assert ')RULES"' not in text
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by loom/tools/gen_semantic_rules.py from core/semantic.py - DO NOT EDIT.\n"
        'static constexpr std::string_view kBuiltinRulesJson = R"RULES(' + text + ')RULES";\n',
        encoding="utf-8",
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
