#!/usr/bin/env python3
"""Extracts the item-cue lexicon from the archive pipeline's C++ tables.

loom/src/archive/items.cpp (kCues, kHeadingHints, negators,
generic_subject_words) and loom/src/archive/text.cpp (stopwords) hold
policy data as C++ literals (the philosophy engine's check
chk.literal_policy_table flags exactly this). This script copies them,
verbatim and in order, into

    loom/data/lexicons/item_cues.json
    loom/data/lexicons/stopwords_base.json

so the paradigm wave can switch items.cpp/text.cpp to the data files with a
byte-identical-output test. Re-run it whenever the C++ tables change until
that switch lands:

    python3 loom/tools/gen_kb_lexicons.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
ITEMS = ROOT / "src/archive/items.cpp"
TEXT = ROOT / "src/archive/text.cpp"
OUT = ROOT / "data/lexicons"


def block(src, start_marker):
    i = src.index(start_marker)
    j = src.index("};", i)
    return src[i:j]


def main():
    items = ITEMS.read_text(encoding="utf-8")
    cues = [
        {"type": t, "phrase": p, "weight": float(w)}
        for t, p, w in re.findall(r'\{"(\w+)",\s*"((?:[^"\\]|\\.)*)",\s*([0-9.]+)\}', block(items, "const Cue kCues[]"))
    ]
    hints = [
        {"phrase": p, "type": t, "weight": float(w)}
        for p, t, w in re.findall(r'\{"((?:[^"\\]|\\.)*)",\s*"(\w+)",\s*([0-9.]+)\}',
                                  block(items, "const HeadingHint kHeadingHints[]"))
    ]
    neg = re.findall(r'"((?:[^"\\]|\\.)*)"', block(items, "negators() {"))
    generic = re.findall(r'"((?:[^"\\]|\\.)*)"', block(items, "generic_subject_words() {"))
    type_order = re.findall(r'"(\w+)"', block(items, "static const char* kOrder[]"))
    text = TEXT.read_text(encoding="utf-8")
    words_block = block(text, "const char* words[] = {")
    sections = {"en": [], "pl": [], "code": []}
    current = None
    for line in words_block.splitlines():
        s = line.strip()
        if s.startswith("// English"):
            current = "en"
        elif s.startswith("// Polish"):
            current = "pl"
        elif s.startswith("// code keywords"):
            current = "code"
        elif current:
            sections[current].extend(re.findall(r'"((?:[^"\\]|\\.)*)"', s))
    OUT.mkdir(parents=True, exist_ok=True)
    item_doc = {
        "schema": "loom.kb.item_cues/1",
        "description": "Generated by loom/tools/gen_kb_lexicons.py from loom/src/archive/items.cpp; verbatim copy of the archive item classifier's cue table (lowercase phrases, trailing '*' = word prefix). Do not edit by hand until items.cpp reads this file.",
        "type_order": type_order,
        "cues": cues,
        "heading_hints": hints,
        "negators": neg,
        "generic_subject_words": generic,
    }
    stop_doc = {
        "schema": "loom.kb.stopwords/1",
        "description": "Generated by loom/tools/gen_kb_lexicons.py from loom/src/archive/text.cpp (archive pipeline v1 stop words, verbatim). stopwords.json extends these for the paradigm wave.",
        "en": sections["en"],
        "pl": sections["pl"],
        "code": sections["code"],
    }
    for name, doc in (("item_cues.json", item_doc), ("stopwords_base.json", stop_doc)):
        (OUT / name).write_text(json.dumps(doc, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"cues={len(cues)} hints={len(hints)} negators={len(neg)} generic={len(generic)} "
          f"stop en={len(sections['en'])} pl={len(sections['pl'])} code={len(sections['code'])}")


if __name__ == "__main__":
    main()
