#!/usr/bin/env python3
"""Generate loom/src/util/unicode_tables.inc from the running CPython.

The C++ predicates in loom/util/unicode.h must agree with Python's `str`
methods and the `re` module, because the Loom kernel re-implements Python code
(core/semantic.py regexes, str.lower(), str.strip(), ...). Instead of
re-deriving the rules from UnicodeData.txt we ask CPython directly.

Usage:  python3 loom/tools/gen_unicode_tables.py  (rewrites the .inc file)
"""
import _sre
import pathlib
import sys
import unicodedata

MAX_CP = 0x10FFFF
OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "util" / "unicode_tables.inc"


def cps():
    for cp in range(MAX_CP + 1):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        yield cp


def ranges(pred):
    out = []
    start = prev = None
    for cp in cps():
        if pred(cp):
            if start is None:
                start = prev = cp
            elif cp == prev + 1:
                prev = cp
            else:
                out.append((start, prev))
                start = prev = cp
    if start is not None:
        out.append((start, prev))
    return out


def simple_lower(cp):
    return _sre.unicode_tolower(cp)


def simple_upper(cp):
    u = chr(cp).upper()
    return ord(u) if len(u) == 1 else cp


def is_cased_for_sigma(cp):
    # Preceding char is cased (and not case-ignorable) -> final sigma.
    return (chr(cp) + "Σ").lower()[-1] == "ς"


def is_case_ignorable(cp):
    return ("Α" + chr(cp) + "Σ").lower()[-1] == "ς" and not is_cased_for_sigma(cp)


def emit_ranges(lines, name, rs):
    lines.append(f"static constexpr CpRange {name}[] = {{")
    row = []
    for lo, hi in rs:
        row.append(f"{{0x{lo:X},0x{hi:X}}}")
        if len(row) == 6:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    lines.append("};")


def main():
    lines = [
        "// GENERATED by loom/tools/gen_unicode_tables.py - DO NOT EDIT.",
        f"// Source: CPython {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}",
        "// Included by src/util/unicode.cpp only.",
        "",
        f'static constexpr const char* kUnicodeVersion = "{unicodedata.unidata_version}";',
        "",
    ]
    emit_ranges(lines, "kAlpha", ranges(lambda c: chr(c).isalpha()))
    emit_ranges(lines, "kDecimal", ranges(lambda c: chr(c).isdecimal()))
    emit_ranges(lines, "kDigit", ranges(lambda c: chr(c).isdigit()))
    emit_ranges(lines, "kNumeric", ranges(lambda c: chr(c).isnumeric()))
    emit_ranges(lines, "kSpace", ranges(lambda c: chr(c).isspace()))
    emit_ranges(lines, "kCased", ranges(is_cased_for_sigma))
    emit_ranges(lines, "kCaseIgnorable", ranges(is_case_ignorable))

    lower = [(c, simple_lower(c)) for c in cps() if simple_lower(c) != c]
    upper = [(c, simple_upper(c)) for c in cps() if simple_upper(c) != c]
    lines.append("static constexpr CpMap kSimpleLower[] = {")
    for i in range(0, len(lower), 6):
        lines.append("  " + ", ".join(f"{{0x{a:X},0x{b:X}}}" for a, b in lower[i:i + 6]) + ",")
    lines.append("};")
    lines.append("static constexpr CpMap kSimpleUpper[] = {")
    for i in range(0, len(upper), 6):
        lines.append("  " + ", ".join(f"{{0x{a:X},0x{b:X}}}" for a, b in upper[i:i + 6]) + ",")
    lines.append("};")

    def special(fn, simple):
        out = []
        for c in cps():
            full = fn(chr(c))
            if full != chr(simple(c)):
                seq = [ord(x) for x in full]
                assert 1 <= len(seq) <= 3, (hex(c), seq)
                out.append((c, seq))
        return out

    for name, entries in (("kFullLower", special(str.lower, simple_lower)),
                          ("kFullUpper", special(str.upper, simple_upper))):
        lines.append(f"static constexpr CpSpecial {name}[] = {{")
        for c, seq in entries:
            padded = seq + [0] * (3 - len(seq))
            lines.append(f"  {{0x{c:X},{len(seq)},{{0x{padded[0]:X},0x{padded[1]:X},0x{padded[2]:X}}}}},")
        if not entries:
            lines.append("  {0,0,{0,0,0}},")
        lines.append("};")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
