#!/usr/bin/env bash
set -euo pipefail
# Same old-API source; actual whole-core archive. No mixed objects.
c++ -DCPPHTTPLIB_OPENSSL_SUPPORT=1 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -DLOOM_BUILDING=1 -DLOOM_HAVE_OPENSSL=1 -DLOOM_VENDORED_SQLITE=1 '-DLOOM_VERSION_STRING="0.1.0"' -I/workspace/scratch/72fc60ad1cc5/chatadhd-baseline/loom/include -I/workspace/scratch/72fc60ad1cc5/chatadhd-baseline/loom/src -isystem /workspace/scratch/72fc60ad1cc5/chatadhd-baseline/loom/third_party/nlohmann -isystem /workspace/scratch/72fc60ad1cc5/chatadhd-baseline/loom/third_party/cpp-httplib -isystem /workspace/scratch/72fc60ad1cc5/chatadhd-baseline/loom/third_party/sqlite -isystem /workspace/scratch/72fc60ad1cc5/chatadhd-baseline/loom/third_party/miniz -std=c++20 -O0 -g0 /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/profile_util_parity.cc /workspace/scratch/72fc60ad1cc5/baseline-build/libloom_core.a /workspace/scratch/72fc60ad1cc5/baseline-build/libloom_miniz.a /workspace/scratch/72fc60ad1cc5/baseline-build/libloom_sqlite3_amalgamation.a -pthread -ldl -lm -lssl -lcrypto -o /workspace/scratch/72fc60ad1cc5/fullcore161-util-before-probe
mkdir -p /workspace/scratch/72fc60ad1cc5/fullcore161-util-before-work
cd /workspace/scratch/72fc60ad1cc5/fullcore161-util-before-work
env -u LOOM_LOG_LEVEL -u LOOM_HTTP_BACKEND LOOM_LOG_STDERR=0 /workspace/scratch/72fc60ad1cc5/fullcore161-util-before-probe > /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-default.before.json 2> /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-default.before.stderr.log
env -u LOOM_LOG_LEVEL -u LOOM_HTTP_BACKEND LOOM_LOG_STDERR=0 LOOM_LOG_LEVEL=DEBUG /workspace/scratch/72fc60ad1cc5/fullcore161-util-before-probe > /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-debug.before.json 2> /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-debug.before.stderr.log
env -u LOOM_LOG_LEVEL -u LOOM_HTTP_BACKEND LOOM_LOG_STDERR=0 LOOM_LOG_LEVEL=warn /workspace/scratch/72fc60ad1cc5/fullcore161-util-before-probe > /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-warning.before.json 2> /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-warning.before.stderr.log
env -u LOOM_LOG_LEVEL -u LOOM_HTTP_BACKEND LOOM_LOG_STDERR=0 LOOM_LOG_LEVEL=error /workspace/scratch/72fc60ad1cc5/fullcore161-util-before-probe > /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-error.before.json 2> /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-error.before.stderr.log
env -u LOOM_LOG_LEVEL -u LOOM_HTTP_BACKEND LOOM_LOG_STDERR=0 LOOM_LOG_LEVEL=unrecognized /workspace/scratch/72fc60ad1cc5/fullcore161-util-before-probe > /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-unknown.before.json 2> /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-unknown.before.stderr.log
env -u LOOM_LOG_LEVEL -u LOOM_HTTP_BACKEND LOOM_LOG_STDERR=0 TMPDIR=/workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/absent-system-temp-fixture /workspace/scratch/72fc60ad1cc5/fullcore161-util-before-probe > /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-fallback.before.json 2> /workspace/scratch/72fc60ad1cc5/chatadhd/docs/reports/data-in-code/evidence/fullcore161/util-fallback.before.stderr.log
