import assert from 'node:assert/strict';
import { createRequire, syncBuiltinESMExports } from 'node:module';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import http from 'node:http';
import https from 'node:https';
import net from 'node:net';
import dgram from 'node:dgram';

const root=process.env.WATCHDOG_AUDIT_REPO!, sha=process.env.WATCHDOG_AUDIT_SHA!;
const mode=process.env.WATCHDOG_AUDIT_MODE!, filter=process.env.WATCHDOG_AUDIT_FILTER ?? '';
const load=(p:string)=>import(pathToFileURL(path.join(root,p)).href);
const require=createRequire(path.join(root,'package.json'));
// Consumer HTTP is injected. Any accidental network path is a hard failure.
let blockedNetworkAttempts=0;
const block=()=>{blockedNetworkAttempts++;throw new Error('AUDIT_EXTERNAL_NETWORK_BLOCKED');};
globalThis.fetch=block as any; http.request=block as any;http.get=block as any;
https.request=block as any;https.get=block as any;net.Socket.prototype.connect=block as any;
dgram.createSocket=block as any;syncBuiltinESMExports();
const started=new Date().toISOString();
const results:any[]=[];
type Trial={id:string; finding:string; category:'reproduction'|'acceptance'; consumer:string; run:()=>any};
const trials:Trial[]=[];
function add(id:string,finding:string,category:Trial['category'],consumer:string,run:Trial['run']){trials.push({id,finding,category,consumer,run});}
const credential={isPresent:true,status:'present',detail:'synthetic audit credential',use:(fn:any)=>fn('AUDIT_FAKE_KEY_NOT_A_CREDENTIAL')};
const response=(body:any)=>({ok:true,status:200,text:async()=>JSON.stringify(body)});
function narrativeInput(api:any){const payload={presetId:null,results:[4,3,2,1].map((v,i)=>({metricKey:'Pi',entityId:['a','b','c','d'][i],valueNumeric:v})),missingCount:0,qualityFlags:[]};return {runId:'audit',payload,payloadHash:api.hashNarrativePayload(payload),templateId:'audit-undefined-template',templateVersion:'999',providerId:null,model:null};}

async function main(){
const narrative=await load('backend/watchdog_api/services/narrative.ts');
const {getPrimitive}=await load('backend/watchdog_api/analysis/primitives.ts');
const {ProfileGenerator}=await load('backend/watchdog_api/llm/profile_generator.ts');
const {buildTextGenerationRegistry}=await load('backend/watchdog_api/llm/index.ts');
const profile=(temperature:number)=>({id:'audit',protocol:'openai',endpoint:'https://example.invalid/audit',headers:{},parameters:{temperature},outputParameter:'max_tokens'});
const ratioInput={numerator:{name:'n',unit:'count',semanticType:'count',entityIds:['absent','present'],values:[null,8]},denominator:{kind:'scalar',unit:'count',value:2}};
const missingOutput=()=>getPrimitive('ratio').run(ratioInput,{missingPolicy:'exclude',params:{}});
add('WD-001-A','WD-001','reproduction','generateNarrative',()=>{const req=narrativeInput(narrative);assert.equal(narrative.generateNarrative(req).content,narrative.generateNarrative({...req,templateId:'other',templateVersion:'1'}).content);return {unknownTemplateAccepted:true};});
add('WD-001-B','WD-001','acceptance','generateNarrative',()=>{assert.throws(()=>narrative.generateNarrative(narrativeInput(narrative)),/template|profile|unknown|unsupported/i);return {unknownTemplateRejected:true};});
add('WD-002-A','WD-002','reproduction','ratio.run',()=>{assert.deepEqual(missingOutput().series.entityIds,['absent','present']);return {missingRowRetained:true};});
add('WD-002-B','WD-002','acceptance','ratio.run',()=>{assert.deepEqual(missingOutput().series.entityIds,['present']);assert.deepEqual(missingOutput().series.values,[4]);return {missingRowExcluded:true};});
async function requestParameters(){let sent:any;const g=new ProfileGenerator(profile(0.6),credential,async (_u:any,i:any)=>{sent=JSON.parse(i.body);return response({model:'audit/model',choices:[{message:{content:'synthetic reply'}}]});},'audit/model',321);await g.generate({prompt:'synthetic audit prompt',model:'audit/model',params:{temperature:0.125,seed:712}});return sent;}
add('WD-003-A','WD-003','reproduction','ProfileGenerator.generate → OpenAiCompatibleGenerator.generate',async()=>{const sent=await requestParameters();assert.equal(sent.temperature,0.6);assert.equal(sent.seed,undefined);return {requestTemperatureIgnored:true,requestSeedIgnored:true};});
add('WD-003-B','WD-003','acceptance','ProfileGenerator.generate → OpenAiCompatibleGenerator.generate',async()=>{try{const sent=await requestParameters();assert.equal(sent.temperature,0.125);assert.equal(sent.seed,712);}catch(e:any){if(e.name==='AssertionError')throw e;assert.match(e.message,/parameter|unsupported|override|conflict/i);}return {requestParametersAppliedOrExplicitlyRejected:true};});
add('WD-011-A','WD-011','reproduction','generateNarrativeWithProvider → assertNoNovelNumbers',async()=>{const req=narrativeInput(narrative);const generator={providerKey:'audit',generate:async()=>({text:'Computed -4 indices.',model:'audit/model',providerKey:'audit',upstreamId:null,usage:{promptTokens:null,completionTokens:null}})};const value=await narrative.generateNarrativeWithProvider({...req,model:'audit/model',generator});assert.equal(value.content,'Computed -4 indices.');assert.equal(value.approvalState,'PROPOSED');return {signChangeAccepted:true,approvalState:value.approvalState};});
add('WD-011-B','WD-011','acceptance','generateNarrativeWithProvider → assertNoNovelNumbers',async()=>{const req=narrativeInput(narrative);const generator={providerKey:'audit',generate:async()=>({text:'Computed -4 indices.',model:'audit/model',providerKey:'audit',upstreamId:null,usage:{promptTokens:null,completionTokens:null}})};await assert.rejects(()=>narrative.generateNarrativeWithProvider({...req,model:'audit/model',generator}),/numeric|fabricat|number/i);return {signChangeRejected:true};});
add('WD-PROFILES-B','WD-003','acceptance','ProfileGenerator.generate',async()=>{const sent:any[]=[];for(const t of [0.1,0.8]){const g=new ProfileGenerator(profile(t),credential,async(_u:any,i:any)=>{sent.push(JSON.parse(i.body));return response({model:'audit/model',choices:[{message:{content:'synthetic'}}]});},'audit/model',321);await g.generate({prompt:'synthetic',model:'audit/model',params:{}});}assert.deepEqual(sent.map(v=>v.temperature),[0.1,0.8]);assert.deepEqual(sent.map(v=>v.max_tokens),[321,321]);return {providerProfilesReachTransport:true};});

async function legacyOverride(){const dir=mkdtempSync(path.join(process.env.WATCHDOG_AUDIT_SCRATCH!,'legacy-'));try{const file=path.join(dir,'provider.json');writeFileSync(file,JSON.stringify({schema_version:'1.0.0',capability:'text.generate',providers:[{provider_key:'audit',display_name:'synthetic audit',endpoint:'https://example.invalid/audit',secret_ref:'env:AUDIT_UNUSED',default_model:'permitted-model',allowed_models:['permitted-model'],generation_params:{model:'disallowed-model',messages:[{role:'user',content:'replacement synthetic prompt'}]}}]}));let sent:any;const registry=buildTextGenerationRegistry(file,{resolve:async()=>credential},async(_u:any,i:any)=>{sent=JSON.parse(i.body);return response({model:sent.model,choices:[{message:{content:'synthetic'}}]});});const generator=await registry.get('audit');await generator.generate({model:'permitted-model',prompt:'intended synthetic prompt',params:await registry.defaultParams('audit')});return sent;}finally{rmSync(dir,{recursive:true,force:true});}}
add('A2-WD-001-A','A2-WD-001','reproduction','loadTextGenerationConfig → TextGenerationRegistry → OpenAiCompatibleGenerator',async()=>{const sent=await legacyOverride();assert.equal(sent.model,'disallowed-model');assert.equal(sent.messages[0].content,'replacement synthetic prompt');return {validatedModelOverwritten:true,validatedPromptOverwritten:true};});
add('A2-WD-001-B','A2-WD-001','acceptance','loadTextGenerationConfig → TextGenerationRegistry → OpenAiCompatibleGenerator',async()=>{try{const sent=await legacyOverride();assert.equal(sent.model,'permitted-model');assert.equal(sent.messages[0].content,'intended synthetic prompt');}catch(e:any){if(e.name==='AssertionError')throw e;assert.match(e.message,/model|messages|parameter|override|reserved|permitted/i);}return {boundFieldsProtected:true};});

const Database=require('better-sqlite3');
const {runMigrations}=await load('backend/watchdog_api/db/migrations/index.ts');
const {SettingsRepository}=await load('backend/watchdog_api/db/repositories/settings.ts');
const {LocalFileSystemStore}=await load('backend/watchdog_api/storage/object_store/index.ts');
const {loadAssistantProfile}=await load('backend/watchdog_api/config/assistant.ts');
const {canonicalHash}=await load('backend/watchdog_api/domain/canonical.ts');
const assistantProfile=loadAssistantProfile();
function harness(){const dir=mkdtempSync(path.join(process.env.WATCHDOG_AUDIT_SCRATCH!,'db-')),dbfile=path.join(dir,'test.sqlite');let db:any;const store=new LocalFileSystemStore(path.join(dir,'objects'));const open=()=>{db=new Database(dbfile);db.pragma('foreign_keys=ON');runMigrations(db);return new SettingsRepository(db,store);};let repo=open();return {get db(){return db;},get repo(){return repo;},store,dir,restart:()=>{db.close();repo=open();},close:()=>{db.close();rmSync(dir,{recursive:true,force:true});}};}
add('WD-SETTINGS-RESTART-B','A2-WD-002','acceptance','SettingsRepository.save/get + runMigrations',()=>{const h=harness();try{const initial=h.repo.get('local-user',assistantProfile.defaults);const value=structuredClone(initial.value);value.assistant.enabled=false;value.assistant.dailyBudgetUsd=0;value.mode='expert';const saved=h.repo.save('local-user',value,initial.hash,assistantProfile.defaults);h.restart();const changedDefaults=structuredClone(assistantProfile.defaults);changedDefaults.assistant.enabled=true;changedDefaults.assistant.dailyBudgetUsd=99;changedDefaults.mode='simple';const restored=h.repo.get('local-user',changedDefaults);assert.deepEqual(restored.value,value);assert.equal(restored.hash,saved.hash);assert.ok(h.db.prepare('SELECT 1 FROM personal_settings_snapshots WHERE hash=?').get(saved.hash));return {restartPreservesDisabled:true,changedPackDefaultsCannotOverrideSavedValue:true,immutableSnapshotAvailable:true};}finally{h.close();}});
add('WD-SETTINGS-INVALID-B','A2-WD-002','acceptance','SettingsRepository.save/get',()=>{const h=harness();try{const initial=h.repo.get('local-user',assistantProfile.defaults);assert.throws(()=>h.repo.save('local-user',{...initial.value,unsupportedAuditPolicy:'silently ignore me'},initial.hash,assistantProfile.defaults));h.repo.save('local-user',initial.value,initial.hash,assistantProfile.defaults);h.db.prepare('UPDATE personal_settings SET body_json=? WHERE owner_principal_id=?').run('{broken','local-user');assert.throws(()=>h.repo.get('local-user',assistantProfile.defaults));return {unknownFieldRejected:true,corruptionRaisesWithoutDefaultReset:true};}finally{h.close();}});
add('WD-ASSISTANT-FAILURE-B','A2-WD-002','acceptance','AssistantService.propose → ProfileGenerator → SettingsRepository.settle',async()=>{const h=harness();try{const {UserVault}=await load('backend/watchdog_api/secrets/user_vault.ts');const {AssistantService}=await load('backend/watchdog_api/services/assistant.ts');const {normalizeModelCatalog}=await load('backend/watchdog_api/llm/routing.ts');const vault=new UserVault(h.repo,path.join(h.dir,'keys/master'),{});const raw=Buffer.from(JSON.stringify({data:[{id:'audit/model',context_length:64000,architecture:{input_modalities:['text'],output_modalities:['text']},pricing:{prompt:'0.000001',completion:'0.000002',request:'0'},supported_parameters:['temperature']}]}));await h.repo.saveCatalog(normalizeModelCatalog(raw,assistantProfile),raw);let calls=0;const service=new AssistantService(h.repo,vault,assistantProfile,async()=>{calls++;throw new Error('synthetic timeout');});await assert.rejects(()=>service.propose('local-user','method_proposal','synthetic'),/Enable/);assert.equal(calls,0);let current=h.repo.get('local-user',assistantProfile.defaults);current=h.repo.save('local-user',{...current.value,assistant:{...current.value.assistant,enabled:true}},current.hash,assistantProfile.defaults);vault.save('local-user','openrouter','AUDIT_FAKE_KEY_NOT_A_CREDENTIAL');await assert.rejects(()=>service.propose('local-user','method_proposal','synthetic'),/reservation is retained/);assert.equal(calls,1);h.restart();const generations=h.repo.generations('local-user');assert.equal(generations.length,1);assert.equal(generations[0].status,'FAILED_RESERVED');assert.equal(generations[0].result.retryAutomatically,false);assert.equal(generations[0].route.settingsHash,current.hash);assert.ok(generations[0].route.routingProfileHash);assert.ok(generations[0].route.providerProfileHash);assert.ok(generations[0].route.catalogHash);return {disabledCalls:0,injectedTimeoutCalls:calls,storedStatus:'FAILED_RESERVED',routeHashesRetained:true};}finally{h.close();}});

for(const t of trials){if(filter&&!t.id.includes(filter))continue;if(mode==='accept'&&t.category!=='acceptance'||mode==='reproduce'&&t.category!=='reproduction')continue;const before=blockedNetworkAttempts;try{const evidence=await t.run();assert.equal(blockedNetworkAttempts,before,'A test tried an actual network path');results.push({...t,run:undefined,status:'PASS',evidence});}catch(e:any){results.push({...t,run:undefined,status:'FAIL',error:{name:e.name,message:String(e.message).slice(0,1000)}});}}
const count=(category:string,status:string)=>results.filter(r=>r.category===category&&r.status===status).length;
const receipt={schema:'klbt.audit.watchdog.pass2/1',repo:'klb-t/Watchdog-JH16',sha,startedAt:started,finishedAt:new Date().toISOString(),node:process.version,scope:'Host TypeScript consumers; file-backed SQLite migrations/restart; injected transports only. No browser/device/cloud/live provider execution.',network:{actualAttemptsBlocked:blockedNetworkAttempts,liveCalls:0,globalFetchBlocked:true,socketConnectBlocked:true},summary:{reproduction:{pass:count('reproduction','PASS'),fail:count('reproduction','FAIL'),meaning:'PASS means the baseline defect was reproduced, never product acceptance.'},acceptance:{pass:count('acceptance','PASS'),fail:count('acceptance','FAIL'),meaning:'FAIL remains a failing product acceptance gate.'}},results};
writeFileSync(process.env.WATCHDOG_AUDIT_OUT!,JSON.stringify(receipt,null,2)+'\n');
console.log(JSON.stringify(receipt.summary));process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
}
main().catch(e=>{console.error(e);process.exitCode=2;});
