// loom/util/unicode.h — Unicode character properties with CPython semantics.
//
// Tables are generated by tools/gen_unicode_tables.py from the CPython that
// runs it (unicodedata + _sre), so the predicates match what Python's `str`
// methods and the `re` module do:
//   is_word    == re `\w` for str patterns   (ch.isalnum() or ch == "_")
//   is_decimal == re `\d`                    (ch.isdecimal())
//   is_space   == re `\s`, str.strip()       (ch.isspace())
//   simple_lower == _sre.unicode_tolower     (used by re.IGNORECASE)
#pragma once

#include <cstddef>
#include <string_view>

namespace loom::unicode {

bool is_alpha(char32_t cp) noexcept;
bool is_decimal(char32_t cp) noexcept;
bool is_digit(char32_t cp) noexcept;
bool is_numeric(char32_t cp) noexcept;
bool is_alnum(char32_t cp) noexcept;  // alpha | decimal | digit | numeric
bool is_space(char32_t cp) noexcept;
bool is_word(char32_t cp) noexcept;   // alnum | '_'

// Simple (1:1) case mappings.
char32_t simple_lower(char32_t cp) noexcept;
char32_t simple_upper(char32_t cp) noexcept;

// Full lowercase / uppercase mapping of one code point, as str.lower()/upper()
// would produce for that character in isolation (final sigma is handled by
// utf8::to_lower). Writes up to 3 code points to `out`, returns the count.
std::size_t full_lower(char32_t cp, char32_t out[3]) noexcept;
std::size_t full_upper(char32_t cp, char32_t out[3]) noexcept;

// Properties for the Final_Sigma rule of str.lower().
bool is_cased(char32_t cp) noexcept;
bool is_case_ignorable(char32_t cp) noexcept;

// Unicode database version the tables were generated from (e.g. "14.0.0").
std::string_view database_version() noexcept;

}  // namespace loom::unicode
